import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/navigation/navbar";
import { Toaster } from "@/app/components/ui/toaster";
import { Footer } from "@/app/components/ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Goalflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${inter.className} h-full bg-axiom-pattern bg-white`}>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        <Toaster />
      </body>
    </html>
  );
}
